import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Footer from '../components/Footer';
import Herosection from '../components/herosection';
import HerosectionNew from '../components/herosectionNew';
import validPageNumbers from '../public/ct_id_valid_page_numbers.json';
import { s3_root_dir } from './contracts_list';
import { s3_root_dir_unlabeled } from './contracts_list';
import { URLListBuilder } from './contracts_list';

export default function Home() {
  let img_list = URLListBuilder(s3_root_dir, 'ct_353', validPageNumbers['ct_353']);
  let img_list_unlabeled = URLListBuilder(s3_root_dir_unlabeled, 'ct_353', validPageNumbers['ct_353']);
  return (
    <div>
      <Head>
        <title>Contract 353</title>
        <meta name="Contract 353" content="Generated by create next app" />
      </Head>
      <HerosectionNew unlabeledImages={img_list} labeledImages={img_list_unlabeled} />
      <Footer />
    </div>
  );
}
