import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div className={styles.container} style={{backgroundColor: 'white', color: 'black', paddingTop: '3em'}}>
      <div className={styles.title}>Hierarchical Contract Segmentation</div>
      <Head>
        <title>CUAD Contract Segmentation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>

      <main className={styles.main}>

        <p className={styles.description}>
          An NYU and Columbia Research Collaboration to advance the state of the art in open source
          legal NLP work. 
        </p>

        <p className={styles.description}>
          We believe the open source machine learning systems analyzing long form documents in the legal domain
          can be improved via a multimodal approach. We aim to improve such systems by incorporating hierarchical 
          document information (such as the structure and layout of documents) in addition to the document's text. This approach aims to improve various downstream tasks that are difficult for 
          current text-only systems due to the length and complexity of legal contracts.   
        </p>

        <div className={styles.grid}>
          <Link href="/contracts_list">
            <div className={styles.card} style={{ cursor: 'pointer' }}>
              <h2>Contracts &rarr;</h2>
              <p>See the currently labeled contracts</p>
            </div>
          </Link>

          {/* <Link href="/image_test">
            <div className={styles.card} style={{ cursor: 'pointer' }}>
              <h2>What we are trying to accomplish &rarr;</h2>
              <p>Advancing the state of the art in legal NLP and vision</p>
            </div>
          </Link>

          <Link href="/image_test">
            <div className={styles.card} style={{ cursor: 'pointer' }}>
              <h2>About us &rarr;</h2>
              <p>Learn about our backgrounds as researchers</p>
            </div>
          </Link> */}
          <Link href="/image_scroll_200">
            <div className={styles.card} style={{ cursor: 'pointer' }}>
              <h2>Example contract &rarr;</h2>
              <p>See a contract labeled using table of contents</p>
            </div>
          </Link>

          <a href="https://github.com/mumose/contract_labeling_with_TOC" className={styles.card}>
            <h2>Github &rarr;</h2>
            <p>Code to help you label and visualize section titles</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
