import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div className={styles.container} style={{backgroundColor: 'white', color: 'black', paddingTop: '3em'}}>
      <div className={styles.title}>Multimodal Contract Segmentation</div>
      <Head>
        <title>CUAD Contract Segmentation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          View contracts <Link href="/contracts_list">here!</Link>
        </h1>

        <h1 className={styles.title}>
          See image scroller <Link href="/image_scroll_200">here!</Link>
        </h1>

        <p className={styles.description}>
          An NYU and Columbia Research Collaboration to advance the state of the art in open source
          legal NLP work
        </p>

        <div className={styles.grid}>
          <Link href="/contracts_list">
            <div className={styles.card} style={{ cursor: 'pointer' }}>
              <h2>See all labeled contracts &rarr;</h2>
              <p>We labeled all contracts with tables of contents</p>
            </div>
          </Link>

          <Link href="/image_test">
            <div className={styles.card} style={{ cursor: 'pointer' }}>
              <h2>What we are trying to accomplish &rarr;</h2>
              <p>Advancing the state of the art in legal NLP and vision</p>
            </div>
          </Link>

          <Link href="/image_test">
            <div className={styles.card} style={{ cursor: 'pointer' }}>
              <h2>About us &rarr;</h2>
              <p>Learn about our backgrounds as researchers</p>
            </div>
          </Link>

          <a href="https://github.com/mumose/contract_labeling_with_TOC" className={styles.card}>
            <h2>Our Github &rarr;</h2>
            <p>Code to help you label and visualize section titles</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
